name: test workflows
on:
  push: 
    branches: 
      - main
  pull_request:
    branches:
      -main
jobs:
  lint:
    name: checking errors
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: '24'
      - name: install dependencies
        run: npm ci
      - name: run lint
        run: npm run lint
  deploy:
    needs: lint
    name: demo deploy to aws
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: '24'
      - name: install dependencies
        run: npm ci
      - name: build project
        run: npm run build
      - name: deploy to aws
        run: echo "Deploying to AWS..."
     

